#!/bin/bash -ex

yum install -y epel-release
yum install -y python-pip
pip install --upgrade ansible
ansible-galaxy install vincentclee.glances --force
ansible-playbook ~/.ansible/roles/vincentclee.glances/playbook.yml
